create table USER (
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    primary key(USERNAME)
);

create table ACCOUNT (
    ACCOUNT_ID VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    BALANCE DECIMAL NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    primary key(ACCOUNT_ID)
);

create table TRANSACTION (
    TRANSACTION_ID INT AUTO_INCREMENT,
    FROM_ACCOUNT VARCHAR(255) NOT NULL,
    TO_ACCOUNT VARCHAR(255) NOT NULL,
    AMOUNT DECIMAL NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    NOTE VARCHAR(1000),
    executed BOOL NOT NULL,
    primary key(TRANSACTION_ID)
);

INSERT INTO USER(USERNAME, PASSWORD) VALUES ('bob','h3ll0bob');
INSERT INTO USER(USERNAME, PASSWORD) VALUES ('eve','c140eve');
INSERT INTO USER(USERNAME, PASSWORD) VALUES ('alice','h1alice');

INSERT INTO ACCOUNT VALUES('1-123456-11','bob', 20000, 'CHF');
INSERT INTO ACCOUNT VALUES('2-123456-22','eve', 20000, 'CHF');
INSERT INTO ACCOUNT VALUES('3-123456-33','alice', 20000, 'CHF');

COMMIT;

select count(*) from TRANSACTION;

delete from TRANSACTION;
update ACCOUNT set balance = 20000;
